"""
COLUMNS
-------

List of columns to display:

::

    TABLE_COLUMNS = (
        'Study',
        'Disease',

Available column_names: 'Aliquot Id', 'Analyte Type', 'Assembly',
'Barcode', 'Center', 'Center Name', 'Checksum', 'Disease', 'Disease Name',
'Files Size', 'Library Type', 'Modified', 'Participant Id', 'Platform',
'Platform Name', 'Published', 'Reason', 'Sample Id', 'Sample Accession',
'Sample Type', 'Sample Type Name', 'State', 'Study', 'TSS Id',
'Uploaded', 'Analysis Id'.

Styles of the columns:

::

    COLUMN_STYLES = {
        'Analysis Id': {
            'width': 220, 'align': 'left', 'default_state': 'visible',
        },
        'Assembly': {
            'width': 120, 'align': 'left', 'default_state': 'visible',
        },

If style for column will be not specified, will be used default styles:

::

    {
        'width': 100,
        'align': 'left',
        'default_state': 'visible'
    }

Available align values: center, justify, left, right, inherit.
Available default_state values: 'visible', 'hidden'.

VALUE_RESOLVERS
---------------

Some column values can has an absurd names.
This variable used to map them to something a human would understand.

Format:
dict <Column name>:<function>

function receives value should be displayed and api result
(api result is a dict, example: {'state': 'live', 'study': 'CCLE', ...})
and should return new value, for example:

::

    def study_resolver(value, result):
        if value.find('Other_Sequencing_Multiisolate') != -1:
            return 'CCLE'
        return value

    def some_field_resolver(value, result):
        if result['state'] == 'live':
            return value
        return ''

    VALUE_RESOLVERS = {
        'Study': study_resolver,
        'Some Field': some_field_resolver,
    }

ROW_MENU_ITEMS
--------------

Allows to add custom table row menu items.
Every custom menu item should consist from menu item name and link
(every custom menu item is just a link).
Details menu item (open item details popup) adds by default.

Format:
list <Menu item name>, <function that returns link>

Example:

::

    def details_page_menu_item(values):
        return reverse('item_details', args=(values.get('analysis_id'),))

    ROW_MENU_ITEMS = [
        ('Show details in new window', details_page_menu_item),
        ...
    ]

values - row data dict.
Menu item will be shown only if link is not None.

"""
import urllib

from django.core.urlresolvers import reverse


COLUMN_STYLES = {
    'Aliquot Id': {
        'width': 300, 'align': 'left', 'default_state': 'hidden',
        },
    'Analysis Id': {
        'width': 300, 'align': 'left', 'default_state': 'visible',
        },
    'Analyte Type': {
        'width': 120, 'align': 'left', 'default_state': 'hidden',
        },
    'Assembly': {
        'width': 170, 'align': 'left', 'default_state': 'visible',
        },
    'Barcode': {
        'width': 235, 'align': 'left', 'default_state': 'visible',
        },
    'Center': {
        'width': 100, 'align': 'left', 'default_state': 'visible',
        },
    'Center Name': {
        'width': 400, 'align': 'left', 'default_state': 'hidden',
        },
    'Checksum': {
        'width': 300, 'align': 'left', 'default_state': 'hidden',
        },
    'Disease': {
        'width': 65, 'align': 'left', 'default_state': 'visible',
        },
    'Disease Name': {
        'width': 200, 'align': 'left', 'default_state': 'hidden',
        },
    'Filename': {
        'width': 400, 'align': 'left', 'default_state': 'hidden',
        },
    'Files Size': {
        'width': 75, 'align': 'right', 'default_state': 'visible',
        },
    'Library Type': {
        'width': 100, 'align': 'left', 'default_state': 'visible',
        },
    'Modified': {
        'width': 80, 'align': 'left', 'default_state': 'visible',
        },
    'Participant Id': {
        'width': 300, 'align': 'left', 'default_state': 'hidden',
        },
    'Platform': {
        'width': 100, 'align': 'left', 'default_state': 'visible',
        },
    'Platform Name': {
        'width': 200, 'align': 'left', 'default_state': 'hidden',
        },
    'Published': {
        'width': 80, 'align': 'left', 'default_state': 'hidden',
        },
    'Sample Accession': {
        'width': 120, 'align': 'left', 'default_state': 'hidden',
        },
    'Sample Id': {
        'width': 300, 'align': 'left', 'default_state': 'hidden',
        },
    'Sample Type': {
        'width': 100, 'align': 'left', 'default_state': 'visible',
        },
    'Sample Type Name': {
        'width': 150, 'align': 'left', 'default_state': 'hidden',
        },
    'State': {
        'width': 70, 'align': 'left', 'default_state': 'visible',
        },
    'Study': {
        'width': 100, 'align': 'left', 'default_state': 'visible',
        },
    'TSS Id': {
        'width': 200, 'align': 'left', 'default_state': 'hidden',
        },
    'Uploaded': {
        'width': 80, 'align': 'left', 'default_state': 'hidden',
        },
}


TABLE_COLUMNS = (
    'Study',
    'Barcode',
    'Disease',
    'Disease Name',
    'Sample Type',
    'Sample Type Name',
    'Analyte Type',
    'Library Type',
    'Center',
    'Center Name',
    'Platform',
    'Platform Name',
    'Assembly',
    'Filename',
    'Files Size',
    'Checksum',
    'Analysis Id',
    'Aliquot Id',
    'Participant Id',
    'Sample Id',
    'TSS Id',
    'Sample Accession',
    'Published',
    'Uploaded',
    'Modified',
    'State',
)

# Use 'Files' field to place files list into Details table
# (every file will be displayed in three rows: Filename, Files Size, Checksum)

DETAILS_FIELDS = (
    'Study',
    'Barcode',
    'Disease',
    'Disease Name',
    'Sample Type',
    'Sample Type Name',
    'Analyte Type',
    'Library Type',
    'Center',
    'Center Name',
    'Platform',
    'Platform Name',
    'Assembly',
    'Files',
    'Analysis Id',
    'Aliquot Id',
    'Participant Id',
    'Sample Id',
    'TSS Id',
    'Sample Accession',
    'Published',
    'Uploaded',
    'Modified',
    'State',
    'Reason',
)

# study id to name
study_id_to_name = {
    "TCGA": "TCGA",  # FIXME not sure why TCGA comes in instead of phs000178
    "TCGA Benchmark": "TCGA Benchmark",
    "phs000178": "TCGA",
    "Homo sapiens Other_Sequencing_Multiisolate": "CCLE",
    "phs000218": "TARGET",
    "phs000463": "TARGET (ALL I)",
    "phs000464": "TARGET (ALL II)",
    "phs000465": "TARGET (AML)",
    "phs000466": "TARGET (CCSK)",
    "phs000467": "TARGET (NBL)",
    "phs000468": "TARGET (OS)",
    "phs000469": "TARGET (PPTP)",
    "phs000471": "TARGET (WT)",
    "CGTEST": "CGTEST",
}

# tissue source site and disease study
tss_id_to_description = {
    '01': 'International Genomics Consortium: Ovarian serous cystadenocarcinoma',
    '02': 'MD Anderson Cancer Center: Glioblastoma multiforme',
    '03': 'Lung Cancer Tissue Bank of CALGB: Lung squamous cell carcinoma',
    '04': 'Gynecologic Oncology Group: Ovarian serous cystadenocarcinoma',
    '05': 'Indivumed: Lung adenocarcinoma',
    '06': 'Henry Ford Hospital: Glioblastoma multiforme',
    '07': 'TGen: Cell Line Control',
    '08': 'UCSF: Glioblastoma multiforme',
    '09': 'UCSF: Ovarian serous cystadenocarcinoma',
    '10': 'MD Anderson Cancer Center: Ovarian serous cystadenocarcinoma',
    '11': 'MD Anderson Cancer Center: Lung squamous cell carcinoma',
    '12': 'Duke: Glioblastoma multiforme',
    '13': 'Memorial Sloan Kettering: Ovarian serous cystadenocarcinoma',
    '14': 'Emory University: Glioblastoma multiforme',
    '15': 'Mayo Clinic - Rochester: Glioblastoma multiforme',
    '16': 'Toronto Western Hospital: Glioblastoma multiforme',
    '17': 'Washington University: Lung adenocarcinoma',
    '18': 'Princess Margaret Hospital (Canada): Lung squamous cell carcinoma',
    '19': 'Case Western: Glioblastoma multiforme',
    '20': 'Fox Chase Cancer Center: Ovarian serous cystadenocarcinoma',
    '21': 'Fox Chase Cancer Center: Lung squamous cell carcinoma',
    '22': 'Mayo Clinic - Rochester: Lung squamous cell carcinoma',
    '23': 'Cedars Sinai: Ovarian serous cystadenocarcinoma',
    '24': 'Washington University: Ovarian serous cystadenocarcinoma',
    '25': 'Mayo Clinic - Rochester: Ovarian serous cystadenocarcinoma',
    '26': 'University of Florida: Glioblastoma multiforme',
    '27': 'Milan - Italy, Fondazione IRCCS Instituto Neuroligico C. Besta: Glioblastoma multiforme',
    '28': 'Cedars Sinai: Glioblastoma multiforme',
    '29': 'Duke: Ovarian serous cystadenocarcinoma',
    '30': 'Harvard: Ovarian serous cystadenocarcinoma',
    '31': 'Imperial College: Ovarian serous cystadenocarcinoma',
    '32': 'St. Joseph\'s Hospital (AZ): Glioblastoma multiforme',
    '33': 'Johns Hopkins: Lung squamous cell carcinoma',
    '34': 'University of Pittsburgh: Lung squamous cell carcinoma',
    '35': 'Cureline: Lung adenocarcinoma',
    '36': 'BC Cancer Agency: Ovarian serous cystadenocarcinoma',
    '37': 'Cureline: Lung squamous cell carcinoma',
    '38': 'UNC: Lung adenocarcinoma',
    '39': 'MSKCC: Lung squamous cell carcinoma',
    '40': 'MSKCC: Lung adenocarcinoma',
    '41': 'Christiana Healthcare: Glioblastoma multiforme',
    '42': 'Christiana Healthcare: Ovarian serous cystadenocarcinoma',
    '43': 'Christiana Healthcare: Lung squamous cell carcinoma',
    '44': 'Christiana Healthcare: Lung adenocarcinoma',
    '45': 'St. Joseph\'s Medical Center (MD): Glioblastoma multiforme',
    '46': 'St. Joseph\'s Medical Center (MD): Lung squamous cell carcinoma',
    '47': 'St. Joseph\'s Medical Center (MD): Ovarian serous cystadenocarcinoma',
    '48': 'Princess Margaret Hospital (Canada): Lung adenocarcinoma',
    '49': 'Johns Hopkins: Lung adenocarcinoma',
    '50': 'University of Pittsburgh: Lung adenocarcinoma',
    '51': 'UNC: Lung squamous cell carcinoma',
    '52': 'University of Miami: Lung squamous cell carcinoma',
    '53': 'University of Miami: Lung adenocarcinoma',
    '55': 'International Genomics Consortium: Lung adenocarcinoma',
    '56': 'International Genomics Consortium: Lung squamous cell carcinoma',
    '57': 'International Genomics Consortium: Ovarian serous cystadenocarcinoma',
    '58': 'Thoraxklinik at University Hospital Heidelberg: Lung squamous cell carcinoma',
    '59': 'Roswell Park: Ovarian serous cystadenocarcinoma',
    '60': 'Roswell Park: Lung squamous cell carcinoma',
    '61': 'University of Pittsburgh: Ovarian serous cystadenocarcinoma',
    '62': 'Thoraxklinik at University Hospital Heidelberg: Lung adenocarcinoma',
    '63': 'Ontario Institute for Cancer Research: Lung squamous cell carcinoma',
    '64': 'Fox Chase: Lung adenocarcinoma',
    '65': 'Roswell Park: Glioblastoma multiforme',
    '66': 'Indivumed: Lung squamous cell carcinoma',
    '67': 'St Joseph\'s Medical Center (MD): Lung adenocarcinoma',
    '68': 'Washington University - Cleveland Clinic: Lung squamous cell carcinoma',
    '69': 'Washington University - Cleveland Clinic: Lung adenocarcinoma',
    '70': 'ILSBio: Lung squamous cell carcinoma',
    '71': 'ILSBio: Lung adenocarcinoma',
    '72': 'NCH: Ovarian serous cystadenocarcinoma',
    '73': 'Roswell Park: Lung adenocarcinoma',
    '74': 'Swedish Neurosciences: Glioblastoma multiforme',
    '75': 'Ontario Institute for Cancer Research (OICR): Lung adenocarcinoma',
    '76': 'Thomas Jefferson University: Glioblastoma multiforme',
    '77': 'Prince Charles Hospital: Lung squamous cell carcinoma',
    '78': 'Prince Charles Hospital: Lung adenocarcinoma',
    '79': 'Ontario Institute for Cancer Research (OICR)/Ottawa: Lung squamous cell carcinoma',
    '80': 'Ontario Institute for Cancer Research (OICR)/Ottawa: Lung adenocarcinoma',
    '81': 'CHI-Penrose Colorado: Glioblastoma multiforme',
    '82': 'CHI-Penrose Colorado: Lung squamous cell carcinoma',
    '83': 'CHI-Penrose Colorado: Lung adenocarcinoma',
    '84': 'Asterand: Glioblastoma multiforme',
    '85': 'Asterand: Lung squamous cell carcinoma',
    '86': 'Asterand: Lung adenocarcinoma',
    '87': 'International Genomics Consortium: Glioblastoma multiforme',
    '88': 'ABS - Blokhin: Lung squamous cell carcinoma',
    '89': 'ABS - Blokhin: Lung adenocarcinoma',
    '90': 'ABS - IUPUI: Lung squamous cell carcinoma',
    '91': 'ABS - IUPUI: Lung adenocarcinoma',
    '92': 'Washington University - St. Louis: Lung squamous cell carcinoma',
    '93': 'Washington University - St. Louis: Lung adenocarcinoma',
    '94': 'Washington University - Emory: Lung squamous cell carcinoma',
    '95': 'Washington University - Emory: Lung adenocarcinoma',
    '96': 'Washington University - NYU: Lung squamous cell carcinoma',
    '97': 'Washington University - NYU: Lung adenocarcinoma',
    '98': 'Washington University - Alabama: Lung squamous cell carcinoma',
    '99': 'Washington University - Alabama: Lung adenocarcinoma',
    'A1': 'UCSF: Breast invasive carcinoma',
    'A2': 'Walter Reed: Breast invasive carcinoma',
    'A3': 'International Genomics Consortium: Kidney renal clear cell carcinoma',
    'A4': 'International Genomics Consortium: Kidney renal papillary cell carcinoma',
    'A5': 'Cedars Sinai: Uterine Corpus Endometrioid Carcinoma',
    'A6': 'Christiana Healthcare: Colon adenocarcinoma',
    'A7': 'Christiana Healthcare: Breast invasive carcinoma',
    'A8': 'Indivumed: Breast invasive carcinoma',
    'AA': 'Indivumed: Colon adenocarcinoma',
    'AB': 'Washington University: Acute Myeloid Leukemia',
    'AC': 'International Genomics Consortium: Breast invasive carcinoma',
    'AD': 'International Genomics Consortium: Colon adenocarcinoma',
    'AE': 'Washington University: Colon adenocarcinoma',
    'AF': 'Christiana Healthcare: Rectum adenocarcinoma',
    'AG': 'Indivumed: Rectum adenocarcinoma',
    'AH': 'International Genomics Consortium: Rectum adenocarcinoma',
    'AI': 'Washington University: Rectum adenocarcinoma',
    'AJ': 'International Genomics Conosrtium: Uterine Corpus Endometrioid Carcinoma',
    'AK': 'Fox Chase: Kidney renal clear cell carcinoma',
    'AL': 'Fox Chase: Kidney renal papillary cell carcinoma',
    'AM': 'Cureline: Colon adenocarcinoma',
    'AN': 'Cureline: Breast invasive carcinoma',
    'AO': 'MSKCC: Breast invasive carcinoma',
    'AP': 'MSKCC: Uterine Corpus Endometrioid Carcinoma',
    'AQ': 'UNC : Breast invasive carcinoma',
    'AR': 'Mayo: Breast invasive carcinoma',
    'AS': 'St. Joseph\'s Medical Center-(MD): Kidney renal clear cell carcinoma',
    'AT': 'St. Joseph\'s Medical Center-(MD): Kidney renal papillary cell carcinoma',
    'AU': 'St. Joseph\'s Medical Center-(MD): Colon adenocarcinoma',
    'AV': 'NCH: Cell Line Control',
    'AW': 'Cureline: Uterine Corpus Endometrioid Carcinoma',
    'AX': 'Gynecologic Oncology Group: Uterine Corpus Endometrioid Carcinoma',
    'AY': 'UNC: Colon adenocarcinoma',
    'AZ': 'University of Pittsburgh: Colon adenocarcinoma',
    'B0': 'University of Pittsburgh: Kidney renal clear cell carcinoma',
    'B1': 'University of Pittsburgh: Kidney renal papillary cell carcinoma',
    'B2': 'Christiana Healthcare: Kidney renal clear cell carcinoma',
    'B3': 'Christiana Healthcare: Kidney renal papillary cell carcinoma',
    'B4': 'Cureline: Kidney renal clear cell carcinoma',
    'B5': 'Duke: Uterine Corpus Endometrioid Carcinoma',
    'B6': 'Duke: Breast invasive carcinoma',
    'B7': 'Cureline: Stomach adenocarcinoma',
    'B8': 'UNC: Kidney renal clear cell carcinoma',
    'B9': 'UNC: Kidney renal papillary cell carcinoma',
    'BA': 'UNC: Head and Neck squamous cell carcinoma',
    'BB': 'Johns Hopkins: Head and Neck squamous cell carcinoma',
    'BC': 'UNC: Liver hepatocellular carcinoma',
    'BD': 'University of Pittsburgh: Liver hepatocellular carcinoma',
    'BE': 'Curleline: Head and Neck squamous cell carcinoma',
    'BF': 'Cureline: Skin Cutaneous Melanoma',
    'BG': 'University of Pittsburgh: Uterine Corpus Endometrioid Carcinoma',
    'BH': 'University of Pittsburgh: Breast invasive carcinoma',
    'BI': 'University of Pittsburgh: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'BJ': 'University of Pittsburgh: Thyroid carcinoma',
    'BK': 'Christiana Healthcare: Uterine Corpus Endometrioid Carcinoma',
    'BL': 'Christiana Healthcare: Bladder Urothelial Carcinoma',
    'BM': 'UNC: Rectum adenocarcinoma',
    'BP': 'MSKCC: Kidney renal clear cell carcinoma',
    'BQ': 'MSKCC: Kidney renal papillary cell carcinoma',
    'BR': 'Asterand: Stomach adenocarcinoma',
    'BS': 'University of Hawaii: Uterine Corpus Endometrioid Carcinoma',
    'BT': 'University of Pittsburgh: Bladder Urothelial Carcinoma',
    'BV': 'St. Joseph\'s Medical Center-(MD): Brain Lower Grade Glioma',
    'BW': 'St. Joseph\'s Medical Center-(MD): Liver hepatocellular carcinoma',
    'BX': 'St. Joseph\'s Medical Center-(MD): Stomach adenocarcinoma',
    'BY': 'St. Joseph\'s Medical Center-(MD): Head and Neck squamous cell carcinoma',
    'BZ': 'St. Joseph\'s Medical Center-(MD): Thyroid carcinoma',
    'C2': 'St. Joseph\'s Medical Center-(MD): Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'C3': 'St. Joseph\'s Medical Center-(MD): Prostate adenocarcinoma',
    'C4': 'Indivumed: Bladder Urothelial Carcinoma',
    'C5': 'Medical College of Wisconsin: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'C7': 'University of Utah: Breast invasive carcinoma',
    'C8': 'ILSBio: Breast invasive carcinoma',
    'C9': 'ILSBio: Head and Neck squamous cell carcinoma',
    'CA': 'ILSBio: Colon adenocarcinoma',
    'CB': 'ILSBio: Kidney renal clear cell carcinoma',
    'CC': 'ILSBio: Liver hepatocellular carcinoma',
    'CD': 'ILSBio: Stomach adenocarcinoma',
    'CE': 'ILSBio: Thyroid carcinoma',
    'CF': 'ILSBio: Bladder Urothelial Carcinoma',
    'CG': 'Indivumed: Stomach adenocarcinoma',
    'CH': 'Indivumed: Prostate adenocarcinoma',
    'CI': 'University of Pittsburgh: Rectum adenocarcinoma',
    'CJ': 'MD Anderson Cancer Center: Kidney renal clear cell carcinoma',
    'CK': 'Harvard: Colon adenocarcinoma',
    'CL': 'Harvard: Rectum adenocarcinoma',
    'CM': 'MSKCC: Colon adenocarcinoma',
    'CN': 'University of Pittsburgh: Head and Neck squamous cell carcinoma',
    'CP': 'Swedish Neurosciences: Brain Lower Grade Glioma',
    'CQ': 'University Health Network, Toronto: Head and Neck squamous cell carcinoma',
    'CR': 'Vanderbilt University: Head and Neck squamous cell carcinoma',
    'CS': 'Thomas Jefferson University: Brain Lower Grade Glioma',
    'CU': 'UNC: Bladder Urothelial Carcinoma',
    'CV': 'MD Anderson Cancer Center: Head and Neck squamous cell carcinoma',
    'CW': 'Mayo Clinic - Rochester: Kidney renal clear cell carcinoma',
    'CX': 'Medical College of Georgia: Head and Neck squamous cell carcinoma',
    'CY': 'Ontario Institute for Cancer Research (OICR): Colon adenocarcinoma',
    'CZ': 'Harvard: Kidney renal clear cell carcinoma',
    'D1': 'Mayo Clinic: Uterine Corpus Endometrioid Carcinoma',
    'D3': 'MD Anderson: Skin Cutaneous Melanoma',
    'D5': 'Greater Poland Cancer Center: Colon adenocarcinoma',
    'D6': 'Greater Poland Cancer Center: Head and Neck squamous cell carcinoma',
    'D7': 'Greater Poland Cancer Center: Stomach adenocarcinoma',
    'D8': 'Greater Poland Cancer Center: Breast invasive carcinoma',
    'D9': 'Greater Poland Cancer Center: Skin Cutaneous Melanoma',
    'DA': 'Yale: Skin Cutaneous Melanoma',
    'DB': 'Mayo Clinic - Rochester: Brain Lower Grade Glioma',
    'DC': 'MSKCC: Rectum adenocarcinoma',
    'DD': 'Mayo Clinic - Rochester: Liver hepatocellular carcinoma',
    'DE': 'University of North Carolina: Thyroid carcinoma',
    'DF': 'Ontario Institute for Cancer Research: Uterine Corpus Endometrioid Carcinoma',
    'DG': 'Ontario Institute for Cancer Research: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'DH': 'University of Florida: Brain Lower Grade Glioma',
    'DI': 'MD Anderson: Uterine Corpus Endometrioid Carcinoma',
    'DJ': 'Memorial Sloan Kettering: Thyroid carcinoma',
    'DK': 'Memorial Sloan Kettering: Bladder Urothelial Carcinoma',
    'DM': 'University Of Michigan: Colon adenocarcinoma',
    'DN': 'Washington University: Acute Myeloid Leukemia',
    'DO': 'Medical College of Georgia: Thyroid carcinoma',
    'DQ': 'University Of Michigan: Head and Neck squamous cell carcinoma',
    'DR': 'University of Hawaii: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'DS': 'Cedars Sinai: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'DT': 'ILSBio: Rectum adenocarcinoma',
    'DU': 'Henry Ford Hospital: Brain Lower Grade Glioma',
    'DV': 'NCI Urologic Oncology Branch: Kidney renal clear cell carcinoma',
    'DW': 'NCI Urologic Oncology Branch: Kidney renal papillary cell carcinoma',
    'DX': 'Memorial Sloan Kettering: Sarcoma',
    'DY': 'University Of Michigan: Rectum adenocarcinoma',
    'DZ': 'Mayo Clinic - Rochester: Kidney renal papillary cell carcinoma',
    'E1': 'Duke: Brain Lower Grade Glioma',
    'E2': 'Roswell Park: Breast invasive carcinoma',
    'E3': 'Roswell Park: Thyroid carcinoma',
    'E5': 'Roswell Park: Bladder Urothelial Carcinoma',
    'E6': 'Roswell Park: Uterine Corpus Endometrioid Carcinoma',
    'E7': 'Asterand: Bladder Urothelial Carcinoma',
    'E8': 'Asterand: Thyroid carcinoma',
    'E9': 'Asterand: Breast invasive carcinoma',
    'EA': 'Asterand: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'EB': 'Asterand: Skin Cutaneous Melanoma',
    'EC': 'Asterand: Uterine Corpus Endometrioid Carcinoma',
    'ED': 'Asterand: Liver hepatocellular carcinoma',
    'EE': 'University of Sydney: Skin Cutaneous Melanoma',
    'EF': 'Cureline: Rectum adenocarcinoma',
    'EG': 'St. Joseph\'s Medical Center-(MD): Rectum adenocarcinoma',
    'EH': 'Ontario Institute for Cancer Research (OICR): Rectum adenocarcinoma',
    'EI': 'Greater Poland Cancer Center: Rectum adenocarcinoma',
    'EJ': 'University of Pittsburgh: Prostate adenocarcinoma',
    'EK': 'Gynecologic Oncology Group: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'EL': 'MD Anderson: Thyroid carcinoma',
    'EM': 'University Health Network: Thyroid carcinoma',
    'EN': 'University Health Network: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'EO': 'University Health Network: Uterine Corpus Endometrioid Carcinoma',
    'EP': 'Christiana Healthcare: Liver hepatocellular carcinoma',
    'EQ': 'Christiana Healthcare: Stomach adenocarcinoma',
    'ER': 'University of Pittsburgh: Skin Cutaneous Melanoma',
    'ES': 'University of Florida: Liver hepatocellular carcinoma',
    'ET': 'Johns Hopkins: Thyroid carcinoma',
    'EU': 'CHI-Penrose Colorado: Kidney renal clear cell carcinoma',
    'EV': 'CHI-Penrose Colorado: Kidney renal papillary cell carcinoma',
    'EW': 'University of Miami: Breast invasive carcinoma',
    'EX': 'University of North Carolina: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'EY': 'University of North Carolina: Uterine Corpus Endometrioid Carcinoma',
    'EZ': 'UNC: Brain Lower Grade Glioma',
    'F1': 'UNC: Stomach adenocarcinoma',
    'F2': 'UNC: Pancreatic adenocarcinoma',
    'F4': 'Asterand: Colon adenocarcinoma',
    'F5': 'Asterand: Rectum adenocarcinoma',
    'F6': 'Asterand: Brain Lower Grade Glioma',
    'F7': 'Asterand: Head and Neck squamous cell carcinoma',
    'F8': 'Asterand: Kidney renal clear cell carcinoma',
    'F9': 'Asterand: Kidney renal papillary cell carcinoma',
    'FA': 'Asterand: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'FB': 'Asterand: Pancreatic adenocarcinoma',
    'FC': 'Asterand: Prostate adenocarcinoma',
    'FD': 'BLN - University Of Chicago: Bladder Urothelial Carcinoma',
    'FE': 'Ohio State University: Thyroid carcinoma',
    'FF': 'SingHealth: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'FG': 'Case Western: Brain Lower Grade Glioma',
    'FH': 'CHI-Penrose Colorado: Thyroid carcinoma',
    'FI': 'Washington University: Uterine Corpus Endometrioid Carcinoma',
    'FJ': 'BLN - Baylor: Bladder Urothelial Carcinoma',
    'FK': 'Johns Hopkins: Thyroid carcinoma',
    'FL': 'University of Hawaii - Normal Study: Uterine Corpus Endometrioid Carcinoma',
    'FM': 'International Genomics Consortium: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'FN': 'International Genomics Consortium: Brain Lower Grade Glioma',
    'FP': 'International Genomics Consortium: Stomach adenocarcinoma',
    'FQ': 'Johns Hopkins: Pancreatic adenocarcinoma',
    'FR': 'University of North Carolina: Skin Cutaneous Melanoma',
    'FS': 'Essen: Skin Cutaneous Melanoma',
    'FT': 'BLN - University of Miami: Bladder Urothelial Carcinoma',
    'FU': 'International Genomics Consortium: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'FV': 'International Genomics Consortium: Liver hepatocellular carcinoma',
    'FW': 'International Genomics Consortium: Skin Cutaneous Melanoma',
    'FX': 'International Genomics Consortium: Sarcoma',
    'FY': 'International Genomics Consortium: Thyroid carcinoma',
    'FZ': 'University of Pittsburgh: Pancreatic adenocarcinoma',
    'G1': 'Asterand: Acute Myeloid Leukemia',
    'G2': 'MD Anderson: Bladder Urothelial Carcinoma',
    'G3': 'Alberta Health Services: Liver hepatocellular carcinoma',
    'G4': 'Roswell Park: Colon adenocarcinoma',
    'G5': 'Roswell Park: Rectum adenocarcinoma',
    'G6': 'Roswell Park: Kidney renal clear cell carcinoma',
    'G7': 'Roswell Park: Kidney renal papillary cell carcinoma',
    'G8': 'Roswell Park: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'G9': 'Roswell Park: Prostate adenocarcinoma',
    'GC': 'International Genomics Consortium: Bladder Urothelial Carcinoma',
    'GD': 'ABS - IUPUI: Bladder Urothelial Carcinoma',
    'GE': 'ABS - IUPUI: Thyroid carcinoma',
    'GF': 'ABS - IUPUI: Skin Cutaneous Melanoma',
    'GG': 'ABS - IUPUI: Uterine Corpus Endometrioid Carcinoma',
    'GH': 'ABS - IUPUI: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'GI': 'ABS - IUPUI: Breast invasive carcinoma',
    'GJ': 'ABS - IUPUI: Liver hepatocellular carcinoma',
    'GK': 'ABS - IUPUI: Kidney renal clear cell carcinoma',
    'GL': 'ABS - IUPUI: Kidney renal papillary cell carcinoma',
    'GM': 'MD Anderson: Breast invasive carcinoma',
    'GN': 'Roswell: Skin Cutaneous Melanoma',
    'GP': 'MD Anderson: Acute Myeloid Leukemia',
    'GR': 'University of Nebraska Medical Center (UNMC): Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'GS': 'University of Barcelona: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'GT': 'ABS - Blokhin: Colon adenocarcinoma',
    'GU': 'BLN - UT Southwestern Medical Center at Dallas: Bladder Urothelial Carcinoma',
    'GV': 'BLN - Cleveland Clinic: Bladder Urothelial Carcinoma',
    'GW': 'ABS - Blokhin: Stomach adenocarcinoma',
    'GX': 'ABS - Blokhin: Prostate adenocarcinoma',
    'GY': 'ABS - Blokhin: Kidney renal papillary cell carcinoma',
    'GZ': 'BC Cancer Agency: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'H1': 'Medical College of Georgia: Stomach adenocarcinoma',
    'H2': 'Christiana Healthcare: Thyroid carcinoma',
    'H3': 'ABS - IUPUI: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'H4': 'Medical College of Georgia: Bladder Urothelial Carcinoma',
    'H5': 'Medical College of Georgia: Uterine Corpus Endometrioid Carcinoma',
    'H6': 'Christiana Healthcare: Pancreatic adenocarcinoma',
    'H7': 'ABS - IUPUI: Head and Neck squamous cell carcinoma',
    'H8': 'ABS - IUPUI: Pancreatic adenocarcinoma',
    'H9': 'ABS - IUPUI: Prostate adenocarcinoma',
    'HA': 'Alberta Health Services: Stomach adenocarcinoma',
    'HB': 'University of North Carolina: Sarcoma',
    'HC': 'International Genomics Consortium: Prostate adenocarcinoma',
    'HD': 'International Genomics Consortium: Head and Neck squamous cell carcinoma',
    'HE': 'Ontario Institute for Cancer Research (OICR): Kidney renal papillary cell carcinoma',
    'HF': 'Ontario Institute for Cancer Research (OICR): Stomach adenocarcinoma',
    'HG': 'Roswell Park: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'HH': 'Fox Chase: Stomach adenocarcinoma',
    'HI': 'Fox Chase: Prostate adenocarcinoma',
    'HJ': 'Fox Chase: Stomach adenocarcinoma',
    'HK': 'Fox Chase: Brain Lower Grade Glioma',
    'HL': 'Fox Chase: Head and Neck squamous cell carcinoma',
    'HM': 'Christiana Healthcare: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'HN': 'Ontario Institute for Cancer Research (OICR): Breast invasive carcinoma',
    'HP': 'Ontario Institute for Cancer Research (OICR): Liver hepatocellular carcinoma',
    'HQ': 'Ontario Institute for Cancer Research (OICR): Bladder Urothelial Carcinoma',
    'HR': 'Ontario Institute for Cancer Research (OICR): Skin Cutaneous Melanoma',
    'HS': 'Ontario Institute for Cancer Research (OICR): Sarcoma',
    'HT': 'Case Western - St Joes: Brain Lower Grade Glioma',
    'HU': 'National Cancer Center Korea: Stomach adenocarcinoma',
    'HV': 'National Cancer Center Korea: Pancreatic adenocarcinoma',
    'HW': 'MSKCC: Brain Lower Grade Glioma',
    'HY': 'Gynecologic Oncology Group: Sarcoma',
    'HZ': 'International Genomics Consortium: Pancreatic adenocarcinoma',
    'IA': 'Cleveland Clinic: Kidney renal papillary cell carcinoma',
    'IB': 'Alberta Health Services: Pancreatic adenocarcinoma',
    'IC': 'University of Pittsburgh: Esophageal carcinoma',
    'ID': 'ABS - IUPUI: Acute Myeloid Leukemia',
    'IE': 'ABS - IUPUI: Sarcoma',
    'IF': 'University of Texas MD Anderson Cancer Center: Sarcoma',
    'IG': 'Asterand: Esophageal carcinoma',
    'IH': 'University of Miami: Skin Cutaneous Melanoma',
    'IJ': 'Christiana Healthcare: Acute Myeloid Leukemia',
    'IK': 'Christiana Healthcare: Brain Lower Grade Glioma',
    'IM': 'University of Miami: Thyroid carcinoma',
    'IN': 'University of Pittsburgh: Stomach adenocarcinoma',
    'IP': 'ABS - IUPUI: Stomach adenocarcinoma',
    'IQ': 'University of Miami: Head and Neck squamous cell carcinoma',
    'IR': 'Memorial Sloan Kettering: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'IS': 'Memorial Sloan Kettering: Sarcoma',
    'IT': 'University of Texas MD Anderson Cancer Center: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'IU': 'University of Texas MD Anderson Cancer Center: Sarcoma',
    'IV': 'International Genomics Consortium: Acute Myeloid Leukemia',
    'IW': 'Cedars Sinai: Sarcoma',
    'IX': 'ABS - Lahey Clinic: Brain Lower Grade Glioma',
    'IY': 'ABS - Lahey Clinic: Head and Neck squamous cell carcinoma',
    'IZ': 'ABS - Lahey Clinic: Kidney renal papillary cell carcinoma',
    'J1': 'ABS - Lahey Clinic: Lung squamous cell carcinoma',
    'J2': 'ABS - Lahey Clinic: Lung adenocarcinoma',
    'J3': 'ABS - Lahey Clinic: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'J4': 'ABS - Lahey Clinic: Prostate adenocarcinoma',
    'J5': 'ABS - Lahey Clinic: Stomach adenocarcinoma',
    'J6': 'St. Joseph\'s Medical Center-(MD): Bladder Urothelial Carcinoma',
    'J7': 'ILSBio: Kidney renal papillary cell carcinoma',
    'J8': 'Mayo Clinic: Thyroid carcinoma',
    'J9': 'Melbourne Health: Prostate adenocarcinoma',
    'JA': 'ABS - Research Metrics Pakistan: Head and Neck squamous cell carcinoma',
    'JB': 'ABS - Research Metrics Pakistan: Kidney renal clear cell carcinoma',
    'JC': 'ABS - Research Metrics Pakistan: Kidney renal papillary cell carcinoma',
    'JD': 'ABS - Research Metrics Pakistan: Lung squamous cell carcinoma',
    'JE': 'ABS - Research Metrics Pakistan: Lung adenocarcinoma',
    'JF': 'ABS - Research Metrics Pakistan: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'JG': 'ABS - Research Metrics Pakistan: Pancreatic adenocarcinoma',
    'JH': 'ABS - Research Metrics Pakistan: Prostate adenocarcinoma',
    'JI': 'ABS - Research Metrics Pakistan: Stomach adenocarcinoma',
    'JJ': 'ABS - Research Metrics Pakistan: Acute Myeloid Leukemia',
    'JK': 'ABS - Research Metrics Pakistan: Bladder Urothelial Carcinoma',
    'JL': 'ABS - Research Metrics Pakistan: Breast invasive carcinoma',
    'JM': 'ABS - Research Metrics Pakistan: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'JN': 'ABS - Research Metrics Pakistan: Sarcoma',
    'JO': 'ABS - Research Metrics Pakistan: Uterine Corpus Endometrioid Carcinoma',
    'JP': 'ABS - Research Metrics Pakistan: Esophageal carcinoma',
    'JQ': 'ABS - Research Metrics Pakistan: Skin Cutaneous Melanoma',
    'JR': 'ABS - Research Metrics Pakistan: Liver hepatocellular carcinoma',
    'JS': 'ABS - Research Metrics Pakistan: Thyroid carcinoma',
    'JT': 'MD Anderson Cancer Center: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'JU': 'BLN - Baylor: Uterine Corpus Endometrioid Carcinoma',
    'JV': 'BLN - Baylor: Sarcoma',
    'JW': 'BLN - Baylor: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'JX': 'Washington University: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'JY': 'University Health Network: Esophageal carcinoma',
    'JZ': 'University of Rochester: Esophageal carcinoma',
    'K1': 'University of Pittsburgh: Sarcoma',
    'K2': 'ABS - Lahey Clinic: Acute Myeloid Leukemia',
    'K3': 'ABS - Lahey Clinic: Breast invasive carcinoma',
    'K4': 'ABS - Lahey Clinic: Bladder Urothelial Carcinoma',
    'K5': 'ABS - Lahey Clinic: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'K6': 'ABS - Lahey Clinic: Uterine Corpus Endometrioid Carcinoma',
    'K7': 'ABS - Lahey Clinic: Liver hepatocellular carcinoma',
    'K8': 'ABS - Lahey Clinic: Skin Cutaneous Melanoma',
    'K9': 'ABS - Lahey Clinic: Thyroid carcinoma',
    'KA': 'ABS - Lahey Clinic: Esophageal carcinoma',
    'KB': 'University Health Network, Toronto: Stomach adenocarcinoma',
    'KC': 'Cornell Medical College: Prostate adenocarcinoma',
    'KD': 'Mount Sinai School of Medicine: Sarcoma',
    'KE': 'Mount Sinai School of Medicine: Uterine Corpus Endometrioid Carcinoma',
    'KF': 'Christiana Healthcare: Sarcoma',
    'KG': 'Baylor Network: Pancreatic adenocarcinoma',
    'KH': 'Memorial Sloan Kettering: Esophageal carcinoma',
    'KJ': 'University of Miami: Uterine Corpus Endometrioid Carcinoma',
    'KK': 'MD Anderson Cancer Center: Prostate adenocarcinoma',
    'KL': 'MSKCC: Kidney Chromophobe',
    'KM': 'NCI Urologic Oncology Branch: Kidney Chromophobe',
    'KN': 'Harvard: Kidney Chromophobe',
    'KO': 'MD Anderson Cancer Center: Kidney Chromophobe',
    'KP': 'British Columbia Cancer Agency: Uterine Corpus Endometrioid Carcinoma',
    'KQ': 'Cornell Medical College: Bladder Urothelial Carcinoma',
    'KR': 'University Of Michigan: Liver hepatocellular carcinoma',
    'KS': 'University Of Michigan: Thyroid carcinoma',
    'KT': 'Hartford: Brain Lower Grade Glioma',
    'KU': 'Hartford: Head and Neck squamous cell carcinoma',
    'KV': 'Hartford: Kidney renal papillary cell carcinoma',
    'KW': 'Hartford: Lung squamous cell carcinoma',
    'KX': 'Hartford: Lung adenocarcinoma',
    'KY': 'Hartford: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'KZ': 'Hartford: Stomach adenocarcinoma',
    'L1': 'Hartford: Pancreatic adenocarcinoma',
    'L2': 'Hartford: Prostate adenocarcinoma',
    'L3': 'Gundersen Lutheran Health System: Lung squamous cell carcinoma',
    'L4': 'Gundersen Lutheran Health System: Lung adenocarcinoma',
    'L5': 'University of Michigan: Esophageal carcinoma',
    'L6': 'National Institutes of Health: Thyroid carcinoma',
    'L7': 'Christiana Care: Esophageal carcinoma',
    'L8': 'University of Miami: Kidney renal papillary cell carcinoma',
    'L9': 'Candler: Lung adenocarcinoma',
    'LA': 'Candler: Lung squamous cell carcinoma',
    'LB': 'Candler: Pancreatic adenocarcinoma',
    'LC': 'Hartford Hospital: Bladder Urothelial Carcinoma',
    'LD': 'Hartford Hospital: Breast invasive carcinoma',
    'LE': 'Hartford Hospital: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'LF': 'Hartford Hospital: Esophageal carcinoma',
    'LG': 'Hartford Hospital: Liver hepatocellular carcinoma',
    'LH': 'Hartford Hospital: Skin Cutaneous Melanoma',
    'LI': 'Hartford Hospital: Sarcoma',
    'LJ': 'Hartford Hospital: Thyroid carcinoma',
    'LK': 'University of Pittsburgh: Mesothelioma',
    'LL': 'Candler: Breast invasive carcinoma',
    'LM': 'Candler: Kidney renal papillary cell carcinoma',
    'LN': 'ILSBIO: Esophageal carcinoma',
    'LP': 'ILSBIO: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'LQ': 'Gundersen Lutheran Health System: Breast invasive carcinoma',
    'LR': 'Gundersen Lutheran Health System: Thyroid carcinoma',
    'LS': 'Gundersen Lutheran Health System: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'LT': 'Gundersen Lutheran Health System: Bladder Urothelial Carcinoma',
    'LU': 'ABS - Blokhin: Bladder Urothelial Carcinoma',
    'LV': 'ABS - Blokhin: Liver hepatocellular carcinoma',
    'LW': 'ABS - Blokhin: Esophageal carcinoma',
    'LX': 'ABS - Blokhin: Uterine Corpus Endometrioid Carcinoma',
    'LY': 'ABS - Blokhin: Sarcoma',
    'LZ': 'ABS - Blokhin: Thyroid carcinoma',
    'M1': 'ABS - Blokhin: Acute Myeloid Leukemia',
    'M2': 'ABS - Blokhin: Breast invasive carcinoma',
    'M3': 'ABS - Blokhin: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'M4': 'ABS - Blokhin: Skin Cutaneous Melanoma',
    'M5': 'Greater Poland Cancer Center: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'M6': 'Greater Poland Cancer Center: Sarcoma',
    'M7': 'University of North Carolina: Prostate adenocarcinoma',
    'M8': 'Ontario Institute for Cancer Research (OICR): Pancreatic adenocarcinoma',
    'M9': 'Ontario Institute for Cancer Research (OICR): Esophageal carcinoma',
    'MA': 'MD Anderson Cancer Center: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'MB': 'University of Minnesota: Sarcoma',
    'MC': 'University of Minnesota: Thyroid carcinoma',
    'MD': 'University of Minnesota: Kidney renal papillary cell carcinoma',
    'ME': 'University of Minnesota: Lung adenocarcinoma',
    'MF': 'University of Minnesota: Lung squamous cell carcinoma',
    'MG': 'BLN - Baylor: Prostate adenocarcinoma',
    'MH': 'BLN - Baylor: Kidney renal papillary cell carcinoma',
    'MI': 'BLN - Baylor: Liver hepatocellular carcinoma',
    'MJ': 'BLN - Baylor: Sarcoma',
    'MK': 'BLN - Baylor: Thyroid carcinoma',
    'ML': 'BLN - Baylor: Lung squamous cell carcinoma',
    'MM': 'BLN - Baylor: Kidney renal clear cell carcinoma',
    'MN': 'BLN - Baylor: Lung adenocarcinoma',
    'MO': 'ILSBio: Sarcoma',
    'MP': 'Washington University - Mayo Clinic: Lung adenocarcinoma',
    'MQ': 'Washington University - NYU: Mesothelioma',
    'MR': 'University of Minnesota: Liver hepatocellular carcinoma',
    'MS': 'University of Minnesota: Breast invasive carcinoma',
    'MT': 'University of Minnesota: Head and Neck squamous cell carcinoma',
    'MU': 'University of Minnesota: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'MV': 'University of Minnesota: Bladder Urothelial Carcinoma',
    'MW': 'University of Miami: Kidney renal clear cell carcinoma',
    'MX': 'MSKCC: Stomach adenocarcinoma',
    'MY': 'Montefiore Medical Center: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'MZ': 'Montefiore Medical Center: Head and Neck squamous cell carcinoma',
    'N1': 'Montefiore Medical Center: Sarcoma',
    'N2': 'Southwestern Medical Center at Dallas: Kidney renal papillary cell carcinoma',
    'N3': 'Southwestern Medical Center at Dallas: Kidney renal clear cell carcinoma',
    'N4': 'Southwestern Medical Center at Dallas: Kidney Chromophobe',
    'N5': 'MSKCC: Uterine Carcinosarcoma',
    'N6': 'University of Pittsburgh: Uterine Carcinosarcoma',
    'N7': 'Washington University: Uterine Carcinosarcoma',
    'N8': 'University of North Carolina: Uterine Carcinosarcoma',
    'N9': 'MD Anderson: Uterine Carcinosarcoma',
    'NA': 'Duke University: Uterine Carcinosarcoma',
    'NB': 'Washington University - CHUV: Lung adenocarcinoma',
    'NC': 'Washington University - CHUV: Lung squamous cell carcinoma',
    'ND': 'Cedars Sinai: Uterine Carcinosarcoma',
    'NE': 'University of Miami: Uterine Carcinosarcoma',
    'NF': 'Mayo Clinic - Rochester: Uterine Carcinosarcoma',
    'NG': 'Roswell Park: Uterine Carcinosarcoma',
    'NH': 'Candler: Colon adenocarcinoma',
    'NI': 'Roswell Park: Liver hepatocellular carcinoma',
    'NJ': 'Washington University - Rush University: Lung adenocarcinoma',
    'NK': 'Washington University - Rush University: Lung squamous cell carcinoma',
    'NL': 'Christiana Healthcare: Uterine Carcinosarcoma',
    'NM': 'Cambridge BioSource: Head and Neck squamous cell carcinoma',
    'NN': 'Washington University - Cleveland Clinic: Mesothelioma',
    'NP': 'International Genomics Consortium: Kidney Chromophobe',
    'NQ': 'International Genomics Consortium: Mesothelioma',
    'NR': 'International Genomics Consortium: Uterine Carcinosarcoma',
    'NS': 'Gundersen Lutheran Health System: Skin Cutaneous Melanoma',
    'NT': 'International Genomics Consortium: Esophageal carcinoma',
    'NU': 'LeHigh Valley Health Network: Esophageal carcinoma',
    'NV': 'LeHigh Valley Health Network: Brain Lower Grade Glioma',
    'NW': 'LeHigh Valley Health Network: Lung adenocarcinoma',
    'NX': 'LeHigh Valley Health Network: Lung squamous cell carcinoma',
    'NY': 'LeHigh Valley Health Network: Pancreatic adenocarcinoma',
    'NZ': 'Montefiore Medical Center: Uterine Carcinosarcoma',
    'O1': 'Washington University - CALGB: Lung adenocarcinoma',
    'O2': 'Washington University - CALGB: Lung squamous cell carcinoma',
    'O3': 'Saint Mary\'s Health Care: Head and Neck squamous cell carcinoma',
    'O4': 'Saint Mary\'s Health Care: Bladder Urothelial Carcinoma',
    'O5': 'Saint Mary\'s Health Care: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'O6': 'Saint Mary\'s Health Care: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'O7': 'Saint Mary\'s Health Care: Acute Myeloid Leukemia',
    'O8': 'Saint Mary\'s Health Care: Liver hepatocellular carcinoma',
    'O9': 'Saint Mary\'s Health Care: Kidney renal papillary cell carcinoma',
    'OA': 'Saint Mary\'s Health Care: Brain Lower Grade Glioma',
    'OB': 'Saint Mary\'s Health Care: Lung adenocarcinoma',
    'OC': 'Saint Mary\'s Health Care: Lung squamous cell carcinoma',
    'OD': 'Saint Mary\'s Health Care: Skin Cutaneous Melanoma',
    'OE': 'Saint Mary\'s Health Care: Pancreatic adenocarcinoma',
    'OF': 'Saint Mary\'s Health Care: Prostate adenocarcinoma',
    'OG': 'Saint Mary\'s Health Care: Sarcoma',
    'OH': 'Saint Mary\'s Health Care: Stomach adenocarcinoma',
    'OJ': 'Saint Mary\'s Health Care: Thyroid carcinoma',
    'OK': 'Mount Sinai School of Medicine: Breast invasive carcinoma',
    'OL': 'University of Chicago: Breast invasive carcinoma',
    'OM': 'University of Chicago: Thyroid carcinoma',
    'ON': 'University of Chicago: Pancreatic adenocarcinoma',
    'OP': 'University of Chicago: Stomach adenocarcinoma',
    'OQ': 'MD Anderson: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'OR': 'University of Michigan: Adrenocortical carcinoma',
    'OS': 'Brigham and Women\'s Hospital: Adrenocortical carcinoma',
    'OT': 'National Cancer Institute: Adrenocortical carcinoma',
    'OU': 'Roswell Park: Adrenocortical carcinoma',
    'OV': 'BLN Baylor: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'OW': 'International Genomics Consortium: Miscellaneous',
    'OX': 'University of North Carolina: Glioblastoma multiforme',
    'OY': 'University of North Carolina: Ovarian serous cystadenocarcinoma',
    'OZ': 'Washington University - Aichi: Lung squamous cell carcinoma',
    'P1': 'University of Minnesota: Uterine Carcinosarcoma',
    'P2': 'Candler: Uterine Carcinosarcoma',
    'P3': ' Fred Hutchinson: Head and Neck squamous cell carcinoma',
    'P4': ' MD Anderson Cancer Center: Kidney renal papillary cell carcinoma',
    'P5': 'Cureline: Brain Lower Grade Glioma',
    'P6': 'Translational Genomics Research Institute: Adrenocortical carcinoma',
    'P7': 'Translational Genomics Research Institute: Pheochromocytoma and Paraganglioma',
    'P8': 'University of Pittsburgh: Pheochromocytoma and Paraganglioma',
    'P9': 'University of Minnesota: Pancreatic adenocarcinoma',
    'PA': 'University of Minnesota: Adrenocortical carcinoma',
    'PB': 'University of Minnesota: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'PC': 'Fox Chase: Sarcoma',
    'PD': 'Fox Chase: Liver hepatocellular carcinoma',
    'PE': 'Fox Chase: Breast invasive carcinoma',
    'PF': 'Fox Chase: Adrenocortical carcinoma',
    'PG': 'Montefiore Medical Center: Uterine Corpus Endometrioid Carcinoma',
    'PH': 'Gundersen Lutheran: Acute Myeloid Leukemia',
    'PJ': 'Gundersen Lutheran: Kidney renal papillary cell carcinoma',
    'PK': 'University Health Network: Adrenocortical carcinoma',
    'PL': 'Institute of Human Virology Nigeria: Breast invasive carcinoma',
    'PM': 'Institute of Human Virology Nigeria: Lung squamous cell carcinoma',
    'PN': 'Institute of Human Virology Nigeria: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'PQ': 'University of Colorado Denver: Bladder Urothelial Carcinoma',
    'PR': 'Roswell Park: Pheochromocytoma and Paraganglioma',
    'PS': 'Cedars Sinai: Lung squamous cell carcinoma',
    'PT': 'Maine Medical Center: Sarcoma',
    'PU': 'Maine Medical Center: Pancreatic adenocarcinoma',
    'PV': 'Maine Medical Center: Head and Neck squamous cell carcinoma',
    'PW': 'Maine Medical Center: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'PX': 'Maine Medical Center: Kidney renal papillary cell carcinoma',
    'PY': 'Maine Medical Center: Liver hepatocellular carcinoma',
    'PZ': ' ABS - Lahey Clinic: Pancreatic adenocarcinoma',
    'Q1': 'University of Oklahoma HSC: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'Q2': 'University of Oklahoma HSC: Kidney renal papillary cell carcinoma',
    'Q3': 'University of Oklahoma HSC: Pancreatic adenocarcinoma',
    'Q4': 'Emory University: Acute Myeloid Leukemia',
    'Q5': 'Emory University: Bladder Urothelial Carcinoma',
    'Q6': 'Emory University: Breast invasive carcinoma',
    'Q7': 'Emory University: Uterine Corpus Endometrioid Carcinoma',
    'Q8': 'Emory University: Colon adenocarcinoma',
    'Q9': 'Emory University: Esophageal carcinoma',
    'QA': 'Emory University: Liver hepatocellular carcinoma',
    'QB': 'Emory University: Skin Cutaneous Melanoma',
    'QC': 'Emory University: Sarcoma',
    'QD': 'Emory University: Thyroid carcinoma',
    'QE': 'Emory University: Uterine Carcinosarcoma',
    'QF': 'BLN - Baylor: Uterine Corpus Endometrioid Carcinoma',
    'QG': 'BLN - Baylor: Colon adenocarcinoma',
    'QH': 'Fondazione-Besta: Brain Lower Grade Glioma',
    'QJ': 'Mount Sinai School of Medicine: Ovarian serous cystadenocarcinoma',
    'QK': 'Emory University - Winship Cancer Inst.: Head and Neck squamous cell carcinoma',
    'QL': ' University of Chicago: Colon adenocarcinoma',
    'QM': 'University of Oklahoma HSC: Uterine Carcinosarcoma',
    'QN': 'ILSBio: Uterine Carcinosarcoma',
    'QP': 'University of Chicago: Rectum adenocarcinoma',
    'QQ': 'Roswell Park: Sarcoma',
    'QR': 'National Institutes of Health: Pheochromocytoma and Paraganglioma',
    'QS': 'Candler: Uterine Corpus Endometrioid Carcinoma',
    'QT': 'University of North Carolina: Pheochromocytoma and Paraganglioma',
    'QU': 'Harvard Beth Israel: Prostate adenocarcinoma',
    'QV': 'Instituto Nacional de Cancerologia: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'QW': 'Instituto Nacional de Cancerologia: Stomach adenocarcinoma',
    'QX': 'Biomatrix: Stomach adenocarcinoma',
    'QY': 'Biomatrix: Esophageal carcinoma',
    'QZ': 'CHI-Penrose Colorado: Kidney Chromophobe',
    'R1': 'CHI-Penrose Colorado: Colon adenocarcinoma',
    'R2': 'CHI-Penrose Colorado: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'R3': 'CHI-Penrose Colorado: Bladder Urothelial Carcinoma',
    'R4': 'Maine Medical Center: Esophageal carcinoma',
    'R5': 'MD Anderson Cancer Center: Stomach adenocarcinoma',
    'R6': 'MD Anderson Cancer Center: Esophageal carcinoma',
    'R7': 'Gundersen Lutheran Health System: Head and Neck squamous cell carcinoma',
    'R8': 'MD Anderson: Brain Lower Grade Glioma',
    'R9': 'Candler: Ovarian serous cystadenocarcinoma',
    'RA': 'Candler: Cervical squamous cell carcinoma and endocervical adenocarcinoma',
    'RB': 'Emory University: Pancreatic adenocarcinoma',
    'RC': 'University of Utah: Liver hepatocellular carcinoma',
    'RD': 'Peter MacCallum Cancer Center: Stomach adenocarcinoma',
    'RE': 'Peter MacCallum Cancer Center: Esophageal carcinoma',
    'RF': 'Mayo Clinic - Rochester: Esophageal carcinoma',
    'RG': 'Montefiore Medical Center: Liver hepatocellular carcinoma',
    'RH': 'BLN - Baylor: Head and Neck squamous cell carcinoma',
    'RJ': 'St. Joseph\'s Hospital AZ: Head and Neck squamous cell carcinoma',
    'RK': 'St. Joseph\'s Hospital AZ: Stomach adenocarcinoma',
    'RL': 'St. Joseph\'s Hospital AZ: Pancreatic adenocarcinoma',
    'RM': 'St. Joseph\'s Hospital AZ: Pheochromocytoma and Paraganglioma',
    'RN': 'St. Joseph\'s Hospital AZ: Sarcoma',
    'RP': 'St. Joseph\'s Hospital AZ: Skin Cutaneous Melanoma',
    'RQ': 'St. Joseph\'s Hospital AZ: Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
    'RR': 'St. Joseph\'s Hospital AZ: Glioblastoma multiforme',
    'RS': 'Memorial Sloan Kettering Cancer Center: Head and Neck squamous cell carcinoma',
    'RT': 'Cleveland Clinic Foundation: Pheochromocytoma and Paraganglioma',
    'RU': 'Northwestern University: Colon adenocarcinoma',
    'RV': 'Northwestern University: Pancreatic adenocarcinoma',
    'RW': 'Michigan University: Pheochromocytoma and Paraganglioma',
    'RX': 'University of Minnesota: Pheochromocytoma and Paraganglioma',
    'RY': 'University of California San Francisco: Brain Lower Grade Glioma',
    'S1': 'University of Minnesota: Skin Cutaneous Melanoma',
    'S2': 'Albert Einstein Medical Center: Lung adenocarcinoma',
    'S3': 'Albert Einstein Medical Center: Breast invasive carcinoma',
    'S4': 'University of Chicago: Pancreatic adenocarcinoma',
    'S5': 'University of Oklahoma HSC: Bladder Urothelial Carcinoma',
    'S7': 'University Hospital Motol: Pheochromocytoma and Paraganglioma',
}

# Center abbreviations to full name.
# This information is also maintained in help.py
center_to_center_name = {
    'BCM': 'Baylor College of Medicine',
    'BCCAGSC': 'Canada\'s Michael Smith Genome Sciences Centre',
    'BI': 'Broad Institute of MIT and Harvard',
    'HMS-RK': 'Harvard Medical School',
    'UNC-LCCC': 'University of North Carolina',
    'USC-JHU': 'University of Southern California / Johns Hopkins',
    'WUGSC': 'Washington University School of Medicine',
}

def study_resolver(value, values):
    study = study_id_to_name.get(value)
    if study == None:
        raise Exception("unknown study: \""+ str(value) + "\"")
    return study

def tss_resolver(value, values):
    if (value == None) or (len(value.strip()) == 0):
        return ""  # TARGET/CGCI don't have tss_id due to privacy concerns
    tss_desc = tss_id_to_description.get(value)
    if tss_desc == None:
        return "[" + value + "]"
    else:
        return tss_desc + " [" + value + "]"

def center_name_resolver(value, values):
    return center_to_center_name.get(value, value)

VALUE_RESOLVERS = {
    'Study': study_resolver,
    'TSS Id': tss_resolver,
    'Center Name': center_name_resolver,
}

tcgaDccDataMatrixUrl = "https://tcga-data.nci.nih.gov/tcga/dataAccessMatrix.htm"
tcga_studies = frozenset(["TCGA", "phs000178"])

def sample_metadata_menu_item(values):
    if values["study"] in tcga_studies:
        disease_abbr = values.get("disease_abbr")
        legacy_sample_id = values.get("legacy_sample_id")
        if (disease_abbr == None) or (disease_abbr == ""):
            return None
        return tcgaDccDataMatrixUrl + "?" + urllib.urlencode((
                ("mode", "ApplyFilter"), ("showMatrix", "true"),
                ("sampleList", legacy_sample_id), ("diseaseType", disease_abbr)))
    else:
        return None


def details_page_menu_item(values):
    return reverse('item_details', args=(values.get('analysis_id'),))


ROW_MENU_ITEMS = [
    # Details popup menu item will be shown
    # regardless of this values.
    ('Show details in new window', details_page_menu_item),
    ('Sample metadata at DCC', sample_metadata_menu_item),
]

DEFAULT_FILTERS = {
    'study': ('phs000178','*Other_Sequencing_Multiisolate', 'phs0004*', 'phs000218'),
    'state': ('live',),
}
