#!/bin/bash

#ver=1-3
ver=1-4

echo 'before func'

fetchXsd() {
    echo 'func'
    local w=$1
    wget -nv http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_$ver/SRA.$w.xsd?view=co -O SRA.$w.xsd
}

fetchXsd analysis
fetchXsd common
fetchXsd experiment
fetchXsd run

wget -nv http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-4/SRA.analysis.xsd?view=co -O SRA.analysis.xsd
